In [36]:
import numpy as np

In [37]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

In [38]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
a2

array([[0, 1, 2, 3, 4, 5]])

In [39]:
a.ndim

1

In [40]:
a2.ndim

2

In [41]:
a2.dtype

dtype('int64')

In [42]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
a.ndim

2

In [44]:
a.itemsize

8

In [45]:
type(a)

numpy.ndarray

In [46]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [47]:
type(b)

numpy.ndarray

In [48]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [49]:
a.dtype

dtype('int64')

In [50]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [51]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [52]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [53]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [55]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [56]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [57]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [58]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [59]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [60]:
c = a - b
c

array([20, 29, 38, 47])

In [61]:
b**2

array([0, 1, 4, 9])

In [62]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [63]:
a < 35

array([ True,  True, False, False])

In [64]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [65]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [66]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [67]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [68]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [69]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [70]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [71]:
c.dtype.name

'float64'

In [72]:
d = np.exp(6)
d

403.4287934927351

In [73]:
d.dtype.name

'float64'

In [74]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [75]:
a.sum()

3.1057109529998157

In [76]:
a.min()

0.027559113243068367

In [77]:
a.max()

0.8277025938204418

In [78]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
b.sum(axis=1)

array([ 6, 22, 38])

In [80]:
b.min(axis=1)

array([0, 4, 8])

In [81]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [95]:
np.floor(10 * rg.random((3,4)))

array([[0., 6., 7., 8.],
       [2., 2., 6., 8.],
       [9., 1., 4., 8.]])

In [82]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [96]:
a.shape

(3, 4)

In [97]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [100]:
a.flatten()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [101]:
a.reshape(6, 2)

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [102]:
a.T

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [103]:
a.T.shape

(4, 3)

In [104]:
a.shape

(3, 4)

In [111]:
a.resize(2,6)
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [134]:
a.resize(6,2)
a

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [135]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[4., 5., 0., 6., 9., 8., 8., 6., 2., 7., 2., 8.],
       [0., 8., 1., 3., 3., 6., 1., 3., 0., 2., 4., 1.]])

In [138]:
np.hsplit(a, 6)

[array([[4., 5.],
        [0., 8.]]),
 array([[0., 6.],
        [1., 3.]]),
 array([[9., 8.],
        [3., 6.]]),
 array([[8., 6.],
        [1., 3.]]),
 array([[2., 7.],
        [0., 2.]]),
 array([[2., 8.],
        [4., 1.]])]

In [139]:
np.hsplit(a, (3, 4))

[array([[4., 5., 0.],
        [0., 8., 1.]]),
 array([[6.],
        [3.]]),
 array([[9., 8., 8., 6., 2., 7., 2., 8.],
        [3., 6., 1., 3., 0., 2., 4., 1.]])]