In [20]:
import pandas as pd

In [21]:
dicionario = {}
dicionario['Elemento 1'] = 'Valor 1'
dicionario['Elemento 2'] = 'Valor 2'
dicionario

{'Elemento 1': 'Valor 1', 'Elemento 2': 'Valor 2'}

In [22]:
# dicionario de notas
alunos = {'Beatriz': [10.0, 4.0, 8.0, 10.0],
          'Ana': [4.0, 7.0, 7.5, 10.0],
          'José': [2.0, 4.5, 4.5, 8.0]}
alunos

{'Beatriz': [10.0, 4.0, 8.0, 10.0],
 'Ana': [4.0, 7.0, 7.5, 10.0],
 'José': [2.0, 4.5, 4.5, 8.0]}

In [23]:
# criando o dataframe
df = pd.DataFrame({'Nome': ['Beatriz', 'Alvaro'], 'Sobrenome': ['Nascimento', 'Duarte'], 'Idade': [22, 32]})

# imprimindo o dataframe
df

Nome   Sobrenome  Idade
0  Beatriz  Nascimento     22
1   Alvaro      Duarte     32

In [24]:
# a ideia é dar erro
df_error = pd.DataFrame({'Nome':'Beatriz', 'Idade': 22}, index=range(1,2))
df_error

Nome  Idade
1  Beatriz     22

In [25]:
# criando um dataframe
df = pd.DataFrame({'Nome': ['Braund, Mr. Owen Harris', 'Allen, Mr. William Henry', 'Bonnell, Miss. Elizabeth'],
                   'Idade': [22, 35, 58],
                   'Sexo': ['Masculino', 'Masculino', 'Feminino']})

# visualizando o nosso dataframe
df

Nome  Idade       Sexo
0   Braund, Mr. Owen Harris     22  Masculino
1  Allen, Mr. William Henry     35  Masculino
2  Bonnell, Miss. Elizabeth     58   Feminino

In [26]:
# dicionario de notas
alunos = pd.DataFrame({'nome': ['Ana', 'Beatriz', 'Bernardo', 'Valentin', 'Sofia'],
          'nota': [4.0, 7.0, 7.5, 10.0,15.0],})
alunos
alunos.set_index(['nome'])

nota
nome          
Ana        4.0
Beatriz    7.0
Bernardo   7.5
Valentin  10.0
Sofia     15.0

In [27]:
df = pd.read_csv('salarios.csv')
df
# df.rename(columns={'Name': 'Nome', 'Position Title': 'Cargo', 'Department': 'Departamento', 'Employee Annual Salary': 'Salário Anual'}, inplace=True)
# df


Name            Position Title        Department  \
0          AARON,  ELVIA J          WATER RATE TAKER       WATER MGMNT   
1        AARON,  JEFFERY M            POLICE OFFICER            POLICE   
2           AARON,  KARINA            POLICE OFFICER            POLICE   
3      AARON,  KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4      ABAD JR,  VICENTE M         CIVIL ENGINEER IV       WATER MGMNT   
...                    ...                       ...               ...   
32177   ZYGOWICZ,  PETER J            POLICE OFFICER            POLICE   
32178    ZYMANTAS,  MARK E            POLICE OFFICER            POLICE   
32179  ZYRKOWSKI,  CARLO E            POLICE OFFICER            POLICE   
32180  ZYSKOWSKI,  DARIUSZ   CHIEF DATA BASE ANALYST              DoIT   
32181                  NaN                       NaN               NaN   

      Employee Annual Salary  
0                  $88967.00  
1                  $80778.00  
2                  $80778.00  
3                  $84780.00  
4                 $104736.00  
...                      ...  
32177              $86520.00  
32178              $83616.00  
32179              $86520.00  
32180             $110352.00  
32181                    NaN  

[32182 rows x 4 columns]

In [28]:
# criando novo dataframe
exemplo = pd.DataFrame({'Nome': ['Valentina', 'Anastácio', 'Joseph'], 'Sexo': ['F', 'M', 'M'], 'Dia nascimento': [2, 3, 2]})

# visualizando o dataframe exemplo
exemplo

Nome Sexo  Dia nascimento
0  Valentina    F               2
1  Anastácio    M               3
2     Joseph    M               2

In [29]:
#Criando a nova coluna
exemplo['Mês de nascimento'] = ['Setembro', 'Outubro', 'Julho']

# visualization o dataframe exemplar
exemplo

Nome Sexo  Dia nascimento Mês de nascimento
0  Valentina    F               2          Setembro
1  Anastácio    M               3           Outubro
2     Joseph    M               2             Julho

In [30]:
df.shape

(32182, 4)

In [31]:
df.head()

Name            Position Title        Department  \
0      AARON,  ELVIA J          WATER RATE TAKER       WATER MGMNT   
1    AARON,  JEFFERY M            POLICE OFFICER            POLICE   
2       AARON,  KARINA            POLICE OFFICER            POLICE   
3  AARON,  KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4  ABAD JR,  VICENTE M         CIVIL ENGINEER IV       WATER MGMNT   

  Employee Annual Salary  
0              $88967.00  
1              $80778.00  
2              $80778.00  
3              $84780.00  
4             $104736.00

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32182 entries, 0 to 32181
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Name                    32181 non-null  object
 1   Position Title          32181 non-null  object
 2   Department              32181 non-null  object
 3   Employee Annual Salary  32181 non-null  object
dtypes: object(4)
memory usage: 1005.8+ KB


In [33]:
df.dropna()

Name                  Position Title        Department  \
0          AARON,  ELVIA J                WATER RATE TAKER       WATER MGMNT   
1        AARON,  JEFFERY M                  POLICE OFFICER            POLICE   
2           AARON,  KARINA                  POLICE OFFICER            POLICE   
3      AARON,  KIMBERLEI R        CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4      ABAD JR,  VICENTE M               CIVIL ENGINEER IV       WATER MGMNT   
...                    ...                             ...               ...   
32176  ZYGADLO,  MICHAEL J  FRM OF MACHINISTS - AUTOMOTIVE  GENERAL SERVICES   
32177   ZYGOWICZ,  PETER J                  POLICE OFFICER            POLICE   
32178    ZYMANTAS,  MARK E                  POLICE OFFICER            POLICE   
32179  ZYRKOWSKI,  CARLO E                  POLICE OFFICER            POLICE   
32180  ZYSKOWSKI,  DARIUSZ         CHIEF DATA BASE ANALYST              DoIT   

      Employee Annual Salary  
0                  $88967.00  
1                  $80778.00  
2                  $80778.00  
3                  $84780.00  
4                 $104736.00  
...                      ...  
32176              $97448.00  
32177              $86520.00  
32178              $83616.00  
32179              $86520.00  
32180             $110352.00  

[32181 rows x 4 columns]

In [34]:
df['Employee Annual Salary'].describe()
# df.keys()

count         32181
unique         1106
top       $86520.00
freq           2497
Name: Employee Annual Salary, dtype: object

In [35]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
dates = pd.date_range("20130101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df.head()
df.tail(3)
df.index
df.columns
df.to_numpy()
df2.to_numpy()
df.describe()
df.T
df.sort_index(axis=1, ascending=False)
df.sort_values(by="B")
df["A"]
df[0:3]
df.loc[dates[0]]
df.loc[:, ["A", "B"]]
df.loc["20130102":"20130104", ["A", "B"]]
df.loc["20130102", ["A", "B"]]
df.loc[dates[0], "A"]
df.at[dates[0], "A"]
df.iloc[3]
df.iloc[3:5, 0:2]
df.iloc[[1, 2, 4], [0, 2]]
df.iloc[1:3, :]
df.iloc[:, 1:3]
df.iloc[1, 1]
df.iat[1, 1]

-1.616679977088006

In [36]:
df[df["A"] > 0]

A         B         C         D
2013-01-01  0.448892  1.685493 -0.860522  0.964054
2013-01-03  1.611193  0.293981 -0.551068 -0.491351
2013-01-05  2.125399 -0.101570 -0.894353 -0.429388

In [37]:
df[df > 0]

A         B         C         D
2013-01-01  0.448892  1.685493       NaN  0.964054
2013-01-02       NaN       NaN  1.101444       NaN
2013-01-03  1.611193  0.293981       NaN       NaN
2013-01-04       NaN       NaN  1.098902  1.263591
2013-01-05  2.125399       NaN       NaN       NaN
2013-01-06       NaN       NaN  0.390164  1.580005

In [38]:
df2 = df.copy()

df2["E"] = ["one", "one", "two", "three", "four", "three"]

df2

A         B         C         D      E
2013-01-01  0.448892  1.685493 -0.860522  0.964054    one
2013-01-02 -0.883303 -1.616680  1.101444 -1.511461    one
2013-01-03  1.611193  0.293981 -0.551068 -0.491351    two
2013-01-04 -1.113811 -0.092482  1.098902  1.263591  three
2013-01-05  2.125399 -0.101570 -0.894353 -0.429388   four
2013-01-06 -0.574796 -0.416737  0.390164  1.580005  three

In [39]:
df2[df2["E"].isin(["one", "three"])]

A         B         C         D      E
2013-01-01  0.448892  1.685493 -0.860522  0.964054    one
2013-01-02 -0.883303 -1.616680  1.101444 -1.511461    one
2013-01-04 -1.113811 -0.092482  1.098902  1.263591  three
2013-01-06 -0.574796 -0.416737  0.390164  1.580005  three

In [40]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [41]:
df["F"] = s1
df

A         B         C         D    F
2013-01-01  0.448892  1.685493 -0.860522  0.964054  NaN
2013-01-02 -0.883303 -1.616680  1.101444 -1.511461  1.0
2013-01-03  1.611193  0.293981 -0.551068 -0.491351  2.0
2013-01-04 -1.113811 -0.092482  1.098902  1.263591  3.0
2013-01-05  2.125399 -0.101570 -0.894353 -0.429388  4.0
2013-01-06 -0.574796 -0.416737  0.390164  1.580005  5.0

In [42]:
df.at[dates[5], "A"] = 0
df

A         B         C         D    F
2013-01-01  0.448892  1.685493 -0.860522  0.964054  NaN
2013-01-02 -0.883303 -1.616680  1.101444 -1.511461  1.0
2013-01-03  1.611193  0.293981 -0.551068 -0.491351  2.0
2013-01-04 -1.113811 -0.092482  1.098902  1.263591  3.0
2013-01-05  2.125399 -0.101570 -0.894353 -0.429388  4.0
2013-01-06  0.000000 -0.416737  0.390164  1.580005  5.0

In [47]:
df.iat[0, 0] = 0
df

A         B         C         D    F
2013-01-01  0.000000  0.000000  0.000000  0.964054  NaN
2013-01-02 -0.883303 -1.616680  1.101444 -1.511461  1.0
2013-01-03  1.611193  0.293981 -0.551068 -0.491351  2.0
2013-01-04 -1.113811 -0.092482  1.098902  1.263591  3.0
2013-01-05  2.125399 -0.101570 -0.894353 -0.429388  4.0
2013-01-06  0.000000 -0.416737  0.390164  1.580005  5.0

In [49]:
df.loc[:, "D"] = np.array([5] * len(df))
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  0.000000  5  NaN
2013-01-02 -0.883303 -1.616680  1.101444  5  1.0
2013-01-03  1.611193  0.293981 -0.551068  5  2.0
2013-01-04 -1.113811 -0.092482  1.098902  5  3.0
2013-01-05  2.125399 -0.101570 -0.894353  5  4.0
2013-01-06  0.000000 -0.416737  0.390164  5  5.0

In [50]:
df2 = df.copy()

df2[df2 > 0] = -df2

df2

A         B         C  D    F
2013-01-01  0.000000  0.000000  0.000000 -5  NaN
2013-01-02 -0.883303 -1.616680 -1.101444 -5 -1.0
2013-01-03 -1.611193 -0.293981 -0.551068 -5 -2.0
2013-01-04 -1.113811 -0.092482 -1.098902 -5 -3.0
2013-01-05 -2.125399 -0.101570 -0.894353 -5 -4.0
2013-01-06  0.000000 -0.416737 -0.390164 -5 -5.0

In [66]:
df.columns

Index(['A', 'B', 'C', 'D', 'F'], dtype='object')

In [67]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
df1

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.000000  5  NaN  1.0
2013-01-02 -0.883303 -1.616680  1.101444  5  1.0  1.0
2013-01-03  1.611193  0.293981 -0.551068  5  2.0  NaN
2013-01-04 -1.113811 -0.092482  1.098902  5  3.0  NaN

In [55]:
df1.dropna(how="any")

A        B         C  D    F    E
2013-01-02 -0.883303 -1.61668  1.101444  5  1.0  1.0

In [68]:
df1.fillna(value=5)

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.000000  5  5.0  1.0
2013-01-02 -0.883303 -1.616680  1.101444  5  1.0  1.0
2013-01-03  1.611193  0.293981 -0.551068  5  2.0  5.0
2013-01-04 -1.113811 -0.092482  1.098902  5  3.0  5.0

In [69]:
pd.isna(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

In [79]:
df.mean()

A    0.289913
B   -0.322248
C    0.190848
D    5.000000
F    3.000000
dtype: float64

In [81]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [82]:
df.sub(s, axis="index")

A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03  0.611193 -0.706019 -1.551068  4.0  1.0
2013-01-04 -4.113811 -3.092482 -1.901098  2.0  0.0
2013-01-05 -2.874601 -5.101570 -5.894353  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [88]:
df.apply(np.cumsum)

A         B         C   D     F
2013-01-01  0.000000  0.000000  0.000000   5   NaN
2013-01-02 -0.883303 -1.616680  1.101444  10   1.0
2013-01-03  0.727891 -1.322699  0.550376  15   3.0
2013-01-04 -0.385920 -1.415182  1.649278  20   6.0
2013-01-05  1.739479 -1.516752  0.754925  25  10.0
2013-01-06  1.739479 -1.933489  1.145089  30  15.0

In [90]:
s = pd.Series(np.random.randint(0, 7, size=10))

s

0    5
1    3
2    6
3    4
4    2
5    4
6    5
7    2
8    4
9    1
dtype: int64

In [91]:
s.value_counts()

4    3
5    2
2    2
3    1
6    1
1    1
dtype: int64

In [92]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [93]:
df = pd.DataFrame(np.random.randn(10, 4))

df

0         1         2         3
0 -0.062537  0.131952 -0.518912 -0.435041
1 -0.215043 -1.214865 -1.194082  0.923515
2  0.224883 -0.516399  1.072448 -0.187460
3  0.754479 -0.815824 -0.108847  2.615439
4 -0.204816 -1.425871 -0.466569  0.906273
5 -0.012934 -0.024610  1.424765 -0.525385
6 -1.363810 -0.326067  0.274779  0.438855
7 -0.037871 -1.111637  1.228809 -0.577825
8 -0.998756  0.785647  1.223990  0.122714
9  1.196257  1.280061  0.818292  1.029040

In [96]:
pieces = [df[:3], df[3:7], df[7:]]
pieces
pd.concat(pieces)

0         1         2         3
0 -0.062537  0.131952 -0.518912 -0.435041
1 -0.215043 -1.214865 -1.194082  0.923515
2  0.224883 -0.516399  1.072448 -0.187460
3  0.754479 -0.815824 -0.108847  2.615439
4 -0.204816 -1.425871 -0.466569  0.906273
5 -0.012934 -0.024610  1.424765 -0.525385
6 -1.363810 -0.326067  0.274779  0.438855
7 -0.037871 -1.111637  1.228809 -0.577825
8 -0.998756  0.785647  1.223990  0.122714
9  1.196257  1.280061  0.818292  1.029040

In [98]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})

right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

left

key  lval
0  foo     1
1  foo     2

In [99]:
right

key  rval
0  foo     4
1  foo     5

In [100]:
pd.merge(left, right, on="key")

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [101]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df

A      B         C         D
0  foo    one  1.192851  1.553732
1  bar    one  0.614897 -0.850379
2  foo    two  0.822871 -0.668952
3  bar  three  0.984818  1.206577
4  foo    two  1.095137  0.223943
5  bar    two -0.586848  1.356692
6  foo    one -1.412682  1.995072
7  foo  three -0.193861  1.719140

In [104]:
df.groupby("A").sum()

C         D
A                      
bar  1.012867  1.712891
foo  1.504315  4.822936

In [106]:
df.groupby(["A", "B"]).sum()

C         D
A   B                        
bar one    0.614897 -0.850379
    three  0.984818  1.206577
    two   -0.586848  1.356692
foo one   -0.219832  3.548805
    three -0.193861  1.719140
    two    1.918008 -0.445009

In [112]:
tuples = list(
    zip(
        *[
            ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
            ["one", "two", "one", "two", "one", "two", "one", "two"],
        ]
    )
)


index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])

df2 = df[:4]

df2

A         B
first second                    
bar   one     1.352572  0.315867
      two    -0.360977  1.377016
baz   one     0.479119  1.508618
      two     0.205322 -0.614188

In [113]:
stacked = df2.stack()

stacked

first  second   
bar    one     A    1.352572
               B    0.315867
       two     A   -0.360977
               B    1.377016
baz    one     A    0.479119
               B    1.508618
       two     A    0.205322
               B   -0.614188
dtype: float64

In [114]:
stacked.unstack()

A         B
first second                    
bar   one     1.352572  0.315867
      two    -0.360977  1.377016
baz   one     0.479119  1.508618
      two     0.205322 -0.614188

In [123]:
stacked.unstack(1)

second        one       two
first                      
bar   A  1.352572 -0.360977
      B  0.315867  1.377016
baz   A  0.479119  0.205322
      B  1.508618 -0.614188

In [128]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df

A  B    C         D         E
0     one  A  foo -0.170388  0.827592
1     one  B  foo  0.371054  0.548470
2     two  C  foo  0.664838  1.913666
3   three  A  bar  1.274297  0.105567
4     one  B  bar  0.510950  0.678162
5     one  C  bar  0.536479  0.495124
6     two  A  foo  0.679087  0.615844
7   three  B  foo  0.960361  0.854465
8     one  C  foo  0.712721  0.270321
9     one  A  bar  0.345953  1.214500
10    two  B  bar -0.382609  0.297366
11  three  C  bar -0.526051 -0.491759

In [129]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [130]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [131]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [132]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [133]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [134]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [135]:
c = a - b
c

array([20, 29, 38, 47])

In [137]:
b**2

array([0, 1, 4, 9])